// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package data

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitData() (*Data, func(), error) {
	client := NewEntClient()
	data := ProvideData(client)
	return data, func() {
	}, nil
}
