// Code generated by entc, DO NOT EDIT.

package shop

const (
	// Label holds the string label denoting the shop type in the database.
	Label = "shop"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFloorID holds the string denoting the floor_id field in the database.
	FieldFloorID = "floor_id"
	// FieldRoomNum holds the string denoting the room_num field in the database.
	FieldRoomNum = "room_num"
	// FieldLayer holds the string denoting the layer field in the database.
	FieldLayer = "layer"
	// FieldBuiltUpArea holds the string denoting the built_up_area field in the database.
	FieldBuiltUpArea = "built_up_area"
	// FieldCommunityID holds the string denoting the community_id field in the database.
	FieldCommunityID = "community_id"
	// FieldFeeRate holds the string denoting the fee_rate field in the database.
	FieldFeeRate = "fee_rate"
	// FieldRoomArea holds the string denoting the room_area field in the database.
	FieldRoomArea = "room_area"
	// FieldRent holds the string denoting the rent field in the database.
	FieldRent = "rent"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the shop in the database.
	Table = "shops"
)

// Columns holds all SQL columns for shop fields.
var Columns = []string{
	FieldID,
	FieldFloorID,
	FieldRoomNum,
	FieldLayer,
	FieldBuiltUpArea,
	FieldCommunityID,
	FieldFeeRate,
	FieldRoomArea,
	FieldRent,
	FieldRemark,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
