// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yongliu1992/smartpms/app/property/service/internal/data"
)

// Injectors from wire.go:

func initApp() (*data.Data, func(), error) {
	client := data.NewEntClient()
	dataData, cleanup, err := data.NewData(client)
	if err != nil {
		return nil, nil, err
	}
	return dataData, func() {
		cleanup()
	}, nil
}
