// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Community is the predicate function for community builders.
type Community func(*sql.Selector)

// Shop is the predicate function for shop builders.
type Shop func(*sql.Selector)
